spring:
  security:
    oauth2:
      client: "refresh-token-uri=https://oauth2.googleapis.com/token"

logging:
  level:
    root: "info"
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %highlight(%-5level) %magenta(%logger).%M:%line - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} %-5level %logger.%M:%line - %msg%n"
  file:
    name: "logs/application.log"
